// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// AsyncIteratorMethods represents an arbitrary async Python iterator.
type AsyncIteratorMethods struct {
	o C.PyObject
}

var _ Object = (*AsyncIteratorMethods)(nil)





func (a *AsyncIteratorMethods) c() *C.PyObject {
	return (*C.PyObject)(unsafe.Pointer(a))
}

// Base returns a BaseObject pointer that gives access to the generic methods on
// that type for this object.
func (a *AsyncIteratorMethods) Base() *BaseObject {
	return (*BaseObject)(unsafe.Pointer(a))
}

// Type returns a pointer to the Type that represents the type of this object in
// Python.
func (a *AsyncIteratorMethods) Type() *Type {
	return newType(c(a).ob_type)
}

// Decref decrements a's reference count, a may not be nil.
func (a *AsyncIteratorMethods) Decref() {
	C.decref(c(a))
}

// Incref increments a's reference count, a may not be nil.
func (a *AsyncIteratorMethods) Incref() {
	C.incref(c(a))
}

// IsTrue returns true if the value of a is considered to be True. This is
// equivalent to "if a:" in Python.
func (a *AsyncIteratorMethods) IsTrue() bool {
	ret := C.PyObject_IsTrue(c(a))
	if ret < 0 {
		panic(exception())
	}
	return ret != 0
}

// Not returns true if the value of a is considered to be False. This is
// equivalent to "if not a:" in Python.
func (a *AsyncIteratorMethods) Not() bool {
	ret := C.PyObject_Not(c(a))
	if ret < 0 {
		panic(exception())
	}
	return ret != 0
}

// Free deallocates the storage (in Python) for a. After calling this method,
// a should no longer be used.
func (a *AsyncIteratorMethods) Free() {
	free(a)
}



/*
set fields:
*/

