// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

type Bytes struct {
	abstractObject
	o C.PyBytesObject
}

// BytesType is the Type object that represents the Bytes type.
var BytesType = (*Type)(unsafe.Pointer(&C.PyBytes_Type))

func bytesCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.bytesCheck(c(obj)) != 0
}

func newBytes(obj *C.PyObject) *Bytes {
	return (*Bytes)(unsafe.Pointer(obj))
}

func (b *Bytes) Size() int {
	ret := C.PyObject_Size(c(b))
	if ret < 0 {
		return 0
	}
	return int(ret)
}

func (b *Bytes) GetItemString(key string) (Object, error) {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_GetItemString(c(b), cKey)
	return obj2ObjErr(ret)
}

func (b *Bytes) HasKey(key Object) bool {
	ret := C.PyMapping_HasKey(c(b), c(key))
	return ret > 0
}

func (b *Bytes) HasKeyString(key string) bool {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_HasKeyString(c(b), cKey)
	return ret > 0
}



/*
bf_getbuffer = true
mp_length = true
mp_subscript = true
nb_remainder = true
ob_base = true
sq_concat = true
sq_contains = true
sq_item = true
sq_length = true
sq_repeat = true
tp_alloc = true
tp_as_buffer = true
tp_as_mapping = true
tp_as_number = true
tp_as_sequence = true
tp_basicsize = true
tp_doc = true
tp_flags = true
tp_free = true
tp_getattro = true
tp_hash = true
tp_itemsize = true
tp_iter = true
tp_methods = true
tp_name = true
tp_new = true
tp_repr = true
tp_richcompare = true
tp_str = true
*/

