// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

type Cell struct {
	abstractObject
	o C.PyCellObject
}

// CellType is the Type object that represents the Cell type.
var CellType = (*Type)(unsafe.Pointer(&C.PyCell_Type))

func cellCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.cellCheck(c(obj)) != 0
}

func newCell(obj *C.PyObject) *Cell {
	return (*Cell)(unsafe.Pointer(obj))
}







/*
ob_base = true
tp_basicsize = true
tp_clear = true
tp_dealloc = true
tp_doc = true
tp_flags = true
tp_getattro = true
tp_getset = true
tp_name = true
tp_new = true
tp_repr = true
tp_richcompare = true
tp_traverse = true
*/

