// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// CFunction represents objects of the CFunctionType (or PyCFunctionType
// in the Python API) type.
type CFunction struct {
	abstractObject
	o C.PyCFunctionObject
}

// CFunctionType is the Type object that represents the CFunction type.
var CFunctionType = (*Type)(unsafe.Pointer(&C.PyCFunction_Type))

func cFunctionCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.cFunctionCheck(c(obj)) != 0
}

func newCFunction(obj *C.PyObject) *CFunction {
	return (*CFunction)(unsafe.Pointer(obj))
}



/*
set fields:
  ob_base
  tp_basicsize
  tp_call
  tp_dealloc
  tp_flags
  tp_getattro
  tp_getset
  tp_hash
  tp_members
  tp_methods
  tp_name
  tp_repr
  tp_richcompare
  tp_traverse
  tp_vectorcall_offset
  tp_weaklistoffset
*/

