// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// CFunction represents objects of the CFunctionType (or PyCFunctionType
// in the Python API) type.
type CFunction struct {
	abstractObject
	o C.PyCFunctionObject
}

// CFunctionType is the Type object that represents the CFunction type.
var CFunctionType = (*Type)(unsafe.Pointer(&C.PyCFunction_Type))

func cFunctionCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.cFunctionCheck(c(obj)) != 0
}

func newCFunction(obj *C.PyObject) *CFunction {
	return (*CFunction)(unsafe.Pointer(obj))
}

// Repr returns a String representation of "cf". This is equivalent to the
// Python "repr(cf)".
//
// Return value: New Reference.
func (cf *CFunction) Repr() (Object, error) {
	ret := C.PyObject_Repr(c(cf))
	return obj2ObjErr(ret)
}

// Hash computes and returns the hash value of cf. The equivalent
// Python is "hash(cf)".
func (cf *CFunction) Hash() (int, error) {
	ret := C.PyObject_Hash(c(cf))
	if ret == -1 {
		return 0, exception()
	}
	return int(ret), nil
}

// Call calls cf with the given args and kwds. kwds may be nil, args may not
// (an empty Tuple must be used if no arguments are wanted). Returns the result
// of the call, or an Error on failure.  This is equivalent to
// "cf(*args, **kwds)" in Python.
//
// Return value: New Reference.
func (cf *CFunction) Call(args *Tuple, kwds *Dict) (Object, error) {
	ret := C.PyObject_Call(c(cf), c(args), c(kwds))
	return obj2ObjErr(ret)
}

// HasAttr returns true if "cf" has the attribute "name".  This is equivalent
// to the Python "hasattr(cf, name)".
func (cf *CFunction) HasAttr(name Object) bool {
	ret := C.PyObject_HasAttr(c(cf), c(name))
	if ret == 1 {
		return true
	}
	return false
}

// GetAttr returns the attribute of "cf" with the name "name".  This is
// equivalent to the Python "cf.name".
//
// Return value: New Reference.
func (cf *CFunction) GetAttr(name Object) (Object, error) {
	ret := C.PyObject_GetAttr(c(cf), c(name))
	return obj2ObjErr(ret)
}

// RichCompare compares "cf" with "obj" using the specified operation (LE, GE
// etc.), and returns the result.  The equivalent Python is "cf op obj", where
// op is the corresponding Python operator for op.
//
// Return value: New Reference.
func (cf *CFunction) RichCompare(obj Object, op Op) (Object, error) {
	ret := C.PyObject_RichCompare(c(cf), c(obj), C.int(op))
	return obj2ObjErr(ret)
}

// RichCompare compares "obj" with "obj2" using the specified operation (LE, GE
// etc.), and returns true or false.  The equivalent Python is "obj op obj2",
// where op is the corresponding Python operator for op.
func (cf *CFunction) RichCompareBool(obj Object, op Op) (bool, error) {
	ret := C.PyObject_RichCompareBool(c(cf), c(obj), C.int(op))
	return int2BoolErr(ret)
}



/*
set fields:
  ob_base
  tp_basicsize
  tp_call
  tp_dealloc
  tp_flags
  tp_getattro
  tp_getset
  tp_hash
  tp_members
  tp_methods
  tp_name
  tp_repr
  tp_richcompare
  tp_traverse
  tp_vectorcall_offset
  tp_weaklistoffset
*/

