// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// CMethod represents objects of the CMethodType (or PyCMethodType
// in the Python API) type.
type CMethod struct {
	abstractObject
	o C.PyCMethodObject
}

// CMethodType is the Type object that represents the CMethod type.
var CMethodType = (*Type)(unsafe.Pointer(&C.PyCMethod_Type))

func cMethodCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.cMethodCheck(c(obj)) != 0
}

func newCMethod(obj *C.PyObject) *CMethod {
	return (*CMethod)(unsafe.Pointer(obj))
}



/*
set fields:
  ob_base
  tp_base
  tp_basicsize
  tp_name
*/

