// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// Complex represents objects of the ComplexType (or PyComplexType
// in the Python API) type.
//
// This type implements the Number protocol.
type Complex struct {
	abstractObject
	o C.PyComplexObject
}

// ComplexType is the Type object that represents the Complex type.
var ComplexType = (*Type)(unsafe.Pointer(&C.PyComplex_Type))

func complexCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.complexCheck(c(obj)) != 0
}

func newComplex(obj *C.PyObject) *Complex {
	return (*Complex)(unsafe.Pointer(obj))
}

func (c *Complex) AsNumber() *NumberMethods {
	return (*NumberMethods)(unsafe.Pointer(c.Base()))
}



/*
set fields:
  nb_absolute
  nb_add
  nb_bool
  nb_multiply
  nb_negative
  nb_positive
  nb_power
  nb_subtract
  nb_true_divide
  ob_base
  tp_alloc
  tp_as_number
  tp_basicsize
  tp_doc
  tp_flags
  tp_free
  tp_getattro
  tp_hash
  tp_members
  tp_methods
  tp_name
  tp_new
  tp_repr
  tp_richcompare
*/

