// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

type Dict struct {
	abstractObject
	o C.PyDictObject
}

// DictType is the Type object that represents the Dict type.
var DictType = (*Type)(unsafe.Pointer(&C.PyDict_Type))

func dictCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.dictCheck(c(obj)) != 0
}

func newDict(obj *C.PyObject) *Dict {
	return (*Dict)(unsafe.Pointer(obj))
}

func (d *Dict) Size() int {
	ret := C.PyObject_Size(c(d))
	if ret < 0 {
		return 0
	}
	return int(ret)
}

func (d *Dict) GetItemString(key string) (Object, error) {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_GetItemString(c(d), cKey)
	return obj2ObjErr(ret)
}

func (d *Dict) HasKey(key Object) bool {
	ret := C.PyMapping_HasKey(c(d), c(key))
	return ret > 0
}

func (d *Dict) HasKeyString(key string) bool {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_HasKeyString(c(d), cKey)
	return ret > 0
}

func (d *Dict) DelItem(key Object) error {
	ret := C.PyObject_DelItem(c(d), c(key))
	return int2Err(ret)
}

func (d *Dict) DelItemString(key string) error {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyObject_DelItemString(c(d), cKey)
	return int2Err(ret)
}

func (d *Dict) SetItemString(key string, v Object) error {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_SetItemString(c(d), cKey, c(v))
	return int2Err(ret)
}

/*
mp_ass_subscript = true
mp_length = true
mp_subscript = true
nb_inplace_or = true
nb_or = true
ob_base = true
sq_contains = true
tp_alloc = true
tp_as_mapping = true
tp_as_number = true
tp_as_sequence = true
tp_basicsize = true
tp_clear = true
tp_dealloc = true
tp_doc = true
tp_flags = true
tp_free = true
tp_getattro = true
tp_hash = true
tp_init = true
tp_iter = true
tp_methods = true
tp_name = true
tp_new = true
tp_repr = true
tp_richcompare = true
tp_traverse = true
tp_vectorcall = true
*/

