// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

type Float struct {
	abstractObject
	o C.PyFloatObject
}

// FloatType is the Type object that represents the Float type.
var FloatType = (*Type)(unsafe.Pointer(&C.PyFloat_Type))

func floatCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.floatCheck(c(obj)) != 0
}

func newFloat(obj *C.PyObject) *Float {
	return (*Float)(unsafe.Pointer(obj))
}







/*
nb_absolute = true
nb_add = true
nb_bool = true
nb_divmod = true
nb_float = true
nb_floor_divide = true
nb_int = true
nb_multiply = true
nb_negative = true
nb_positive = true
nb_power = true
nb_remainder = true
nb_subtract = true
nb_true_divide = true
ob_base = true
tp_as_number = true
tp_basicsize = true
tp_dealloc = true
tp_doc = true
tp_flags = true
tp_getattro = true
tp_getset = true
tp_hash = true
tp_methods = true
tp_name = true
tp_new = true
tp_repr = true
tp_richcompare = true
tp_vectorcall = true
*/

