// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// FrameLocalsProxy represents objects of the FrameLocalsProxyType (or PyFrameLocalsProxy_Type
// in the Python API) type.
//
// This type implements the Mapping protocol.
type FrameLocalsProxy struct {
	o C.PyFrameLocalsProxyObject
}

var _ Object = (*FrameLocalsProxy)(nil)

// FrameLocalsProxyType is the Type object that represents the FrameLocalsProxy type.
var FrameLocalsProxyType = newType(&C.PyFrameLocalsProxy_Type)

func frameLocalsProxyCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.frameLocalsProxyCheck(c(obj)) != 0
}

// AsFrameLocalsProxy casts the given obj to a FrameLocalsProxy (i.e. the underlying
// Python Object is the same, just the type is changed). If the value cannot be
// cast to a FrameLocalsProxy, then nil is returned.
//
// Return value: Borrowed Reference.
func AsFrameLocalsProxy(obj Object) *FrameLocalsProxy {
	if obj == nil {
		return nil
	}
	o := c(obj)
	if C.frameLocalsProxyCheck(o) == 0 {
		return nil
	}
	return (*FrameLocalsProxy)(unsafe.Pointer(o))
}

func newFrameLocalsProxy(obj *C.PyObject) *FrameLocalsProxy {
	return (*FrameLocalsProxy)(unsafe.Pointer(obj))
}



func (f *FrameLocalsProxy) c() *C.PyFrameLocalsProxyObject {
	return (*C.PyFrameLocalsProxyObject)(unsafe.Pointer(f))
}

// Base returns a BaseObject pointer that gives access to the generic methods on
// that type for this object.
func (f *FrameLocalsProxy) Base() *BaseObject {
	return (*BaseObject)(unsafe.Pointer(f))
}

// Type returns a pointer to the Type that represents the type of this object in
// Python.
func (f *FrameLocalsProxy) Type() *Type {
	return newType(c(f).ob_type)
}


// Decref decrements f's reference count, f may not be nil.
func (f *FrameLocalsProxy) Decref() {
	obj := (*C.PyObject)(unsafe.Pointer(f))
	refcnt := (*int)(unsafe.Pointer(&obj.anon0[0]))
	if *refcnt >= C._Py_IMMORTAL_MINIMUM_REFCNT {
		return
	}
	*refcnt--
	if *refcnt == 0 {
		C._Py_Dealloc(obj)
	}
}

// Incref increments f's reference count, f may not be nil.
func (f *FrameLocalsProxy) Incref() {
	refcnt := (*int)(unsafe.Pointer(&(*C.PyObject)(unsafe.Pointer(f)).anon0[0]))
	if *refcnt >= C._Py_IMMORTAL_MINIMUM_REFCNT {
		return
	}
	*refcnt++
}

// Repr returns a String representation of "f". This is equivalent to the
// Python "repr(f)".
//
// Return value: New Reference.
func (f *FrameLocalsProxy) Repr() (*Unicode, error) {
	ret := C.PyObject_Repr(c(f))
	if ret == nil {
		return nil, exception()
	}
	return newObject(ret).(*Unicode), nil
}

// HasAttr returns true if "f" has the attribute "name".  This is equivalent
// to the Python "hasattr(f, name)".
func (f *FrameLocalsProxy) HasAttr(name Object) bool {
	ret := C.PyObject_HasAttr(c(f), c(name))
	return ret == 1
}

// GetAttr returns the attribute of "f" with the name "name".  This is
// equivalent to the Python "f.name".
//
// Return value: New Reference.
func (f *FrameLocalsProxy) GetAttr(name Object) (Object, error) {
	ret := C.PyObject_GetAttr(c(f), c(name))
	return obj2ObjErr(ret)
}

// SetAttr sets the attribute of "f" with the name "name" to "value".  This is
// equivalent to the Python "f.name = value".
func (f *FrameLocalsProxy) SetAttr(name, value Object) error {
	ret := C.PyObject_SetAttr(c(f), c(name), c(value))
	return int2Err(ret)
}

// DelAttr deletes the attribute with the name "name" from "f".  This is
// equivalent to the Python "del f.name".
func (f *FrameLocalsProxy) DelAttr(name, value Object) error {
	ret := C.PyObject_SetAttr(c(f), c(name), nil)
	return int2Err(ret)
}

// RichCompare compares "f" with "obj" using the specified operation (LE, GE
// etc.), and returns the result.  The equivalent Python is "f op obj", where
// op is the corresponding Python operator for op.
//
// Return value: New Reference.
func (f *FrameLocalsProxy) RichCompare(obj Object, op Op) (Object, error) {
	ret := C.PyObject_RichCompare(c(f), c(obj), C.int(op))
	return obj2ObjErr(ret)
}

// RichCompare compares "f" with "obj" using the specified operation (LE, GE
// etc.), and returns true or false.  The equivalent Python is "f op obj",
// where op is the corresponding Python operator for op.
func (f *FrameLocalsProxy) RichCompareBool(obj Object, op Op) (bool, error) {
	ret := C.PyObject_RichCompareBool(c(f), c(obj), C.int(op))
	return int2BoolErr(ret)
}

// Iter returns an Iterator that will iterate over the members of f.
func (f *FrameLocalsProxy) Iter() (Iterator, error) {
	ret := C.PyObject_GetIter(c(f))
	if ret == nil {
		return nil, exception()
	}
	return newIterator(ret)
}

// Size returns the size of f. The equivalent Python is "len(f)".
func (f *FrameLocalsProxy) Size() int {
	ret := C.PyObject_Size(c(f))
	if ret < 0 {
		clearErr();
		return 0
	}
	return int(ret)
}

// AsMappingMethods returns a MappingMethods instance that refers to the same
// underlying Python object as f.
//
// This method also means that FrameLocalsProxy implements the MappingProtocol interface.
func (f *FrameLocalsProxy) AsMappingMethods() *MappingMethods {
	return (*MappingMethods)(unsafe.Pointer(f.Base()))
}

func (f *FrameLocalsProxy) GetItemString(key string) (Object, error) {
	cKey := C.CString(key)
	defer cfree(cKey)
	ret := C.PyMapping_GetItemString(c(f), cKey)
	return obj2ObjErr(ret)
}

func (f *FrameLocalsProxy) HasKey(key Object) bool {
	ret := C.PyMapping_HasKey(c(f), c(key))
	clearErr();
	return ret > 0
}

func (f *FrameLocalsProxy) HasKeyString(key string) bool {
	cKey := C.CString(key)
	defer cfree(cKey)
	ret := C.PyMapping_HasKeyString(c(f), cKey)
	clearErr();
	return ret > 0
}

func (f *FrameLocalsProxy) DelItem(key Object) error {
	ret := C.PyObject_DelItem(c(f), c(key))
	return int2Err(ret)
}

func (f *FrameLocalsProxy) DelItemString(key string) error {
	cKey := C.CString(key)
	defer cfree(cKey)
	ret := C.PyObject_DelItemString(c(f), cKey)
	return int2Err(ret)
}

func (f *FrameLocalsProxy) SetItemString(key string, v Object) error {
	cKey := C.CString(key)
	defer cfree(cKey)
	ret := C.PyMapping_SetItemString(c(f), cKey, c(v))
	return int2Err(ret)
}

func (f *FrameLocalsProxy) Contains(obj Object) (bool, error) {
	ret := C.PySequence_Contains(c(f), c(obj))
	return int2BoolErr(ret)
}

// Or returns the bitwise or of f and obj. The equivalent Python is
// "f | obj".
//
// Return value: New Reference.
func (f *FrameLocalsProxy) Or(obj Object) (Object, error) {
	ret := C.PyNumber_Or(c(f), c(obj))
	return obj2ObjErr(ret)
}

// InPlaceOr returns the bitwise or of f and obj. This is done in place. The
// equivalent Python is "f |= obj".
//
// Return value: New Reference.
func (f *FrameLocalsProxy) InPlaceOr(obj Object) (Object, error) {
	ret := C.PyNumber_InPlaceOr(c(f), c(obj))
	return obj2ObjErr(ret)
}



/*
set fields:
  mp_ass_subscript
  mp_length
  mp_subscript
  nb_inplace_or
  nb_or
  ob_base
  sq_contains
  tp_alloc
  tp_as_mapping
  tp_as_number
  tp_as_sequence
  tp_basicsize
  tp_clear
  tp_dealloc
  tp_flags
  tp_free
  tp_getattro
  tp_iter
  tp_methods
  tp_name
  tp_new
  tp_repr
  tp_richcompare
  tp_setattro
  tp_traverse
*/

