// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// Frame represents objects of the FrameType (or PyFrameType
// in the Python API) type.
type Frame struct {
	abstractObject
	o C.PyFrameObject
}

// FrameType is the Type object that represents the Frame type.
var FrameType = (*Type)(unsafe.Pointer(&C.PyFrame_Type))

func frameCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.frameCheck(c(obj)) != 0
}

func newFrame(obj *C.PyObject) *Frame {
	return (*Frame)(unsafe.Pointer(obj))
}

// Repr returns a String representation of "f". This is equivalent to the
// Python "repr(f)".
//
// Return value: New Reference.
func (f *Frame) Repr() (Object, error) {
	ret := C.PyObject_Repr(c(f))
	return obj2ObjErr(ret)
}

// HasAttr returns true if "f" has the attribute "name".  This is equivalent
// to the Python "hasattr(f, name)".
func (f *Frame) HasAttr(name Object) bool {
	ret := C.PyObject_HasAttr(c(f), c(name))
	if ret == 1 {
		return true
	}
	return false
}

// GetAttr returns the attribute of "f" with the name "name".  This is
// equivalent to the Python "f.name".
//
// Return value: New Reference.
func (f *Frame) GetAttr(name Object) (Object, error) {
	ret := C.PyObject_GetAttr(c(f), c(name))
	return obj2ObjErr(ret)
}

// SetAttr sets the attribute of "f" with the name "name" to "value".  This is
// equivalent to the Python "f.name = value".
func (f *Frame) SetAttr(name, value Object) error {
	ret := C.PyObject_SetAttr(c(f), c(name), c(value))
	return int2Err(ret)
}

// DelAttr deletes the attribute with the name "name" from "f".  This is
// equivalent to the Python "del f.name".
func (f *Frame) DelAttr(name, value Object) error {
	ret := C.PyObject_SetAttr(c(f), c(name), nil)
	return int2Err(ret)
}



/*
set fields:
  ob_base
  tp_basicsize
  tp_clear
  tp_dealloc
  tp_flags
  tp_getattro
  tp_getset
  tp_itemsize
  tp_members
  tp_methods
  tp_name
  tp_repr
  tp_setattro
  tp_traverse
*/

