// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

type Function struct {
	abstractObject
	o C.PyFunctionObject
}

// FunctionType is the Type object that represents the Function type.
var FunctionType = (*Type)(unsafe.Pointer(&C.PyFunction_Type))

func functionCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.functionCheck(c(obj)) != 0
}

func newFunction(obj *C.PyObject) *Function {
	return (*Function)(unsafe.Pointer(obj))
}







/*
ob_base = true
tp_basicsize = true
tp_call = true
tp_clear = true
tp_dealloc = true
tp_descr_get = true
tp_dictoffset = true
tp_doc = true
tp_flags = true
tp_getset = true
tp_members = true
tp_name = true
tp_new = true
tp_repr = true
tp_traverse = true
tp_vectorcall_offset = true
tp_weaklistoffset = true
*/

