#!/usr/bin/env python3

import sys


type_map = [
    ("int", "int"),
    ("int8", "int8_t"),
    ("int16", "int16_t"),
    ("int32", "int32_t"),
    ("int64", "int64_t"),
    ("uint", "uint"),
    ("uint8", "uint8_t"),
    ("uint16", "uint16_t"),
    ("uint32", "uint32_t"),
    ("uint64", "uint64_t"),
    ("float32", "float"),
    ("float64", "double"),
]

header = """// Code generated by gen_arg.py. DO NOT EDIT.

// This file is automatically generated.  To regenerate:
//   go generate ./...

package py

// #include "utils.h"
import "C"

import (
	"math"
	"unsafe"
)
"""


def write_header():
    print(header)


def write_calloc():
    print("func calloc(v any) unsafe.Pointer {")
    print("\tswitch v.(type) {")
    print("\tcase *string:")
    print("\t\treturn C.calloc(1, C.size_t(unsafe.Sizeof((*C.char)(nil))))")
    print("\tcase *Object:")
    print("\t\treturn C.calloc(1, C.size_t(unsafe.Sizeof((*C.PyObject)(nil))))")
    for go, c in type_map:
        print(f"\tcase *{go}:")
        print(f"\t\treturn C.calloc(1, C.size_t(unsafe.Sizeof((C.{c})(0))))")
    print("\tdefault:")
    print("\t\treturn nil")
    print("\t}")
    print("}")


def write_unpack():
    print("func unpackValues(cValues []unsafe.Pointer, values []any) error {")
    print("\tdefer func() {")
    print("\t\tfor _, v := range cValues {")
    print("\t\t\tC.free(v)")
    print("\t\t}")
    print("\t}()")
    print()
    print("\tfor i, value := range values {")
    print("\t\tswitch v := value.(type) {")
    print("\t\tcase *string:")
    print("\t\t\t*v = C.GoString(*(**C.char)(cValues[i]))")
    print("\t\tcase *Object:")
    print("\t\t\t*v = newObject(*(**C.PyObject)(cValues[i]))")
    for go, c in type_map:
        print(f"\t\tcase *{go}:")
        print(f"\t\t\t*v = {go}(*(*C.{c})(cValues[i]))")
    print("\t\tdefault:")
    print("\t\t\treturn TypeError.Err(\"Unsupported type: %T\", v)")
    print("\t\t}")
    print("\t}")
    print("\treturn nil")
    print("}")


def ffi_type(c_type):
    t = c_type.removesuffix("_t")
    if t.startswith("int"):
        return "ffi_type_s"+t
    return "ffi_type_"+t


def write_build():
    print("func buildCValues(values []any) ([]C.ArgValue, func(), error) {")
    print("\tcValues := make([]C.ArgValue, len(values))")
    print()
    print("\tvar strings []*C.char")
    print()
    print("\tcleanup := func(){")
    print("\t\tfor _, s := range strings {")
    print("\t\t\tcfree(s)")
    print("\t\t}")
    print("\t}")
    print()
    print("\tfor i, value := range values {")
    print("\t\tswitch v := value.(type) {")
    print("\t\tcase string:")
    print("\t\t\ts := C.CString(v)")
    print("\t\t\tstrings = append(strings, s)")
    print("\t\t\tp := (**C.char)(calloc(&v))")
    print("\t\t\t*p = s")
    print("\t\t\tcValues[i]._type = &C.ffi_type_pointer")
    print("\t\t\tcValues[i].value = unsafe.Pointer(p)")
    print("\t\tcase Object:")
    print("\t\t\tp := (**C.PyObject)(calloc(&v))")
    print("\t\t\t*p = c(v)")
    print("\t\t\tcValues[i]._type = &C.ffi_type_pointer")
    print("\t\t\tcValues[i].value = unsafe.Pointer(p)")
    for go, c in type_map:
        print(f"\t\tcase {go}:")
        print(f"\t\t\tp := (*C.{c})(calloc(&v))")
        print(f"\t\t\t*p = C.{c}(v)")
        if go == "int":
            print("\t\t\tif math.MaxInt == math.MaxInt64 {")
            print(f"\t\t\t\tcValues[i]._type = &C.ffi_type_sint64")
            print("\t\t\t} else {")
            print(f"\t\t\t\tcValues[i]._type = &C.ffi_type_sint32")
            print("\t\t\t}")
        elif go == "uint":
            print("\t\t\tif math.MaxUint == math.MaxUint64 {")
            print(f"\t\t\t\tcValues[i]._type = &C.ffi_type_uint64")
            print("\t\t\t} else {")
            print(f"\t\t\t\tcValues[i]._type = &C.ffi_type_uint32")
            print("\t\t\t}")
        else:
            print(f"\t\t\tcValues[i]._type = &C.{ffi_type(c)}")
        print(f"\t\t\tcValues[i].value = unsafe.Pointer(p)")
    print("\t\tdefault:")
    print("\t\t\treturn nil, nil, TypeError.Err(\"Unsupported type: %T\", v)")
    print("\t\t}")
    print("\t}")
    print()
    print("\treturn cValues, cleanup, nil")
    print("}")


def main():
    with open("arg_gen.go", "w", encoding="utf-8") as f:
        sys.stdout = f
        write_header()
        print()
        write_calloc()
        print()
        write_unpack()
        print()
        write_build()


if __name__ == "__main__":
    main()
