// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// InstanceMethod represents objects of the InstanceMethodType (or PyInstanceMethodType
// in the Python API) type.
type InstanceMethod struct {
	abstractObject
	o C.PyInstanceMethodObject
}

// InstanceMethodType is the Type object that represents the InstanceMethod type.
var InstanceMethodType = (*Type)(unsafe.Pointer(&C.PyInstanceMethod_Type))

func instanceMethodCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.instanceMethodCheck(c(obj)) != 0
}

func newInstanceMethod(obj *C.PyObject) *InstanceMethod {
	return (*InstanceMethod)(unsafe.Pointer(obj))
}

// Repr returns a String representation of "i". This is equivalent to the
// Python "repr(i)".
//
// Return value: New Reference.
func (i *InstanceMethod) Repr() (Object, error) {
	ret := C.PyObject_Repr(c(i))
	return obj2ObjErr(ret)
}



/*
set fields:
  ob_base
  tp_basicsize
  tp_call
  tp_dealloc
  tp_descr_get
  tp_doc
  tp_flags
  tp_getattro
  tp_getset
  tp_members
  tp_name
  tp_new
  tp_repr
  tp_richcompare
  tp_setattro
  tp_traverse
*/

