// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

type List struct {
	abstractObject
	o C.PyListObject
}

// ListType is the Type object that represents the List type.
var ListType = (*Type)(unsafe.Pointer(&C.PyList_Type))

func listCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.listCheck(c(obj)) != 0
}

func newList(obj *C.PyObject) *List {
	return (*List)(unsafe.Pointer(obj))
}

func (l *List) Size() int {
	ret := C.PyObject_Size(c(l))
	if ret < 0 {
		return 0
	}
	return int(ret)
}

func (l *List) GetItemString(key string) (Object, error) {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_GetItemString(c(l), cKey)
	return obj2ObjErr(ret)
}

func (l *List) HasKey(key Object) bool {
	ret := C.PyMapping_HasKey(c(l), c(key))
	return ret > 0
}

func (l *List) HasKeyString(key string) bool {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_HasKeyString(c(l), cKey)
	return ret > 0
}

func (l *List) DelItem(key Object) error {
	ret := C.PyObject_DelItem(c(l), c(key))
	return int2Err(ret)
}

func (l *List) DelItemString(key string) error {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyObject_DelItemString(c(l), cKey)
	return int2Err(ret)
}

func (l *List) SetItemString(key string, v Object) error {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_SetItemString(c(l), cKey, c(v))
	return int2Err(ret)
}

/*
mp_ass_subscript = true
mp_length = true
mp_subscript = true
ob_base = true
sq_ass_item = true
sq_concat = true
sq_contains = true
sq_inplace_concat = true
sq_inplace_repeat = true
sq_item = true
sq_length = true
sq_repeat = true
tp_alloc = true
tp_as_mapping = true
tp_as_sequence = true
tp_basicsize = true
tp_clear = true
tp_dealloc = true
tp_doc = true
tp_flags = true
tp_free = true
tp_getattro = true
tp_hash = true
tp_init = true
tp_iter = true
tp_methods = true
tp_name = true
tp_new = true
tp_repr = true
tp_richcompare = true
tp_traverse = true
tp_vectorcall = true
*/

