// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// MappingMethods is a concrete realisation of the full set of Mapping Protocol
// methods. A type that implements the "Mapping Protocol" can be turned into a
// MappingMethods instance using AsMapping.
//
// Note that the methods not already implemented on the type itself may return
// an error, as not all methods are implemented by all types that support the
// protocol.
type MappingMethods struct {
	o C.PyObject
}

var _ Object = (*MappingMethods)(nil)





func (m *MappingMethods) c() *C.PyObject {
	return (*C.PyObject)(unsafe.Pointer(m))
}

// Base returns a BaseObject pointer that gives access to the generic methods on
// that type for this object.
func (m *MappingMethods) Base() *BaseObject {
	return (*BaseObject)(unsafe.Pointer(m))
}

// Type returns a pointer to the Type that represents the type of this object in
// Python.
func (m *MappingMethods) Type() *Type {
	return newType(c(m).ob_type)
}


// Decref decrements m's reference count, m may not be nil.
func (m *MappingMethods) Decref() {
	obj := (*C.PyObject)(unsafe.Pointer(m))
	refcnt := (*int)(unsafe.Pointer(&obj.anon0[0]))
	if *refcnt == C._Py_IMMORTAL_REFCNT {
		return
	}
	*refcnt--
	if *refcnt == 0 {
		C._Py_Dealloc(obj)
	}
}

// Incref increments m's reference count, m may not be nil.
func (m *MappingMethods) Incref() {
	refcnt := (*int)(unsafe.Pointer(&(*C.PyObject)(unsafe.Pointer(m)).anon0[0]))
	if *refcnt == C._Py_IMMORTAL_REFCNT {
		return
	}
	*refcnt++
}



/*
set fields:
*/

