// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// MemoryView represents objects of the MemoryViewType (or PyMemoryView_Type
// in the Python API) type.
//
// This type implements the Mapping protocol.
//
// This type implements the Sequence protocol.
type MemoryView struct {
	o C.PyMemoryViewObject
}

var _ Object = (*MemoryView)(nil)

// MemoryViewType is the Type object that represents the MemoryView type.
var MemoryViewType = newType(&C.PyMemoryView_Type)

func memoryViewCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.memoryViewCheck(c(obj)) != 0
}

// AsMemoryView casts the given obj to a MemoryView (i.e. the underlying
// Python Object is the same, just the type is changed). If the value cannot be
// cast to a MemoryView, then nil is returned.
//
// Return value: Borrowed Reference.
func AsMemoryView(obj Object) *MemoryView {
	if obj == nil {
		return nil
	}
	o := c(obj)
	if C.memoryViewCheck(o) == 0 {
		return nil
	}
	return (*MemoryView)(unsafe.Pointer(o))
}

func newMemoryView(obj *C.PyObject) *MemoryView {
	return (*MemoryView)(unsafe.Pointer(obj))
}



func (m *MemoryView) c() *C.PyMemoryViewObject {
	return (*C.PyMemoryViewObject)(unsafe.Pointer(m))
}

// Base returns a BaseObject pointer that gives access to the generic methods on
// that type for this object.
func (m *MemoryView) Base() *BaseObject {
	return (*BaseObject)(unsafe.Pointer(m))
}

// Type returns a pointer to the Type that represents the type of this object in
// Python.
func (m *MemoryView) Type() *Type {
	return newType(c(m).ob_type)
}


// Decref decrements m's reference count, m may not be nil.
func (m *MemoryView) Decref() {
	obj := (*C.PyObject)(unsafe.Pointer(m))
	refcnt := (*int)(unsafe.Pointer(&obj.anon0[0]))
	if *refcnt == C._Py_IMMORTAL_REFCNT {
		return
	}
	*refcnt--
	if *refcnt == 0 {
		C._Py_Dealloc(obj)
	}
}

// Incref increments m's reference count, m may not be nil.
func (m *MemoryView) Incref() {
	refcnt := (*int)(unsafe.Pointer(&(*C.PyObject)(unsafe.Pointer(m)).anon0[0]))
	if *refcnt == C._Py_IMMORTAL_REFCNT {
		return
	}
	*refcnt++
}

// Repr returns a String representation of "m". This is equivalent to the
// Python "repr(m)".
//
// Return value: New Reference.
func (m *MemoryView) Repr() (*Unicode, error) {
	ret := C.PyObject_Repr(c(m))
	if ret == nil {
		return nil, exception()
	}
	return newObject(ret).(*Unicode), nil
}

// Hash computes and returns the hash value of m. The equivalent
// Python is "hash(m)".
func (m *MemoryView) Hash() (int, error) {
	ret := C.PyObject_Hash(c(m))
	if ret == -1 {
		return 0, exception()
	}
	return int(ret), nil
}

// HasAttr returns true if "m" has the attribute "name".  This is equivalent
// to the Python "hasattr(m, name)".
func (m *MemoryView) HasAttr(name Object) bool {
	ret := C.PyObject_HasAttr(c(m), c(name))
	return ret == 1
}

// GetAttr returns the attribute of "m" with the name "name".  This is
// equivalent to the Python "m.name".
//
// Return value: New Reference.
func (m *MemoryView) GetAttr(name Object) (Object, error) {
	ret := C.PyObject_GetAttr(c(m), c(name))
	return obj2ObjErr(ret)
}

// RichCompare compares "m" with "obj" using the specified operation (LE, GE
// etc.), and returns the result.  The equivalent Python is "m op obj", where
// op is the corresponding Python operator for op.
//
// Return value: New Reference.
func (m *MemoryView) RichCompare(obj Object, op Op) (Object, error) {
	ret := C.PyObject_RichCompare(c(m), c(obj), C.int(op))
	return obj2ObjErr(ret)
}

// RichCompare compares "m" with "obj" using the specified operation (LE, GE
// etc.), and returns true or false.  The equivalent Python is "m op obj",
// where op is the corresponding Python operator for op.
func (m *MemoryView) RichCompareBool(obj Object, op Op) (bool, error) {
	ret := C.PyObject_RichCompareBool(c(m), c(obj), C.int(op))
	return int2BoolErr(ret)
}

// Iter returns an Iterator that will iterate over the members of m.
func (m *MemoryView) Iter() (Iterator, error) {
	ret := C.PyObject_GetIter(c(m))
	if ret == nil {
		return nil, exception()
	}
	return newIterator(ret)
}

// Size returns the size of m. The equivalent Python is "len(m)".
func (m *MemoryView) Size() int {
	ret := C.PyObject_Size(c(m))
	if ret < 0 {
		clearErr();
		return 0
	}
	return int(ret)
}

// AsMappingMethods returns a MappingMethods instance that refers to the same
// underlying Python object as m.
//
// This method also means that MemoryView implements the MappingProtocol interface.
func (m *MemoryView) AsMappingMethods() *MappingMethods {
	return (*MappingMethods)(unsafe.Pointer(m.Base()))
}

func (m *MemoryView) GetItemString(key string) (Object, error) {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_GetItemString(c(m), cKey)
	return obj2ObjErr(ret)
}

func (m *MemoryView) HasKey(key Object) bool {
	ret := C.PyMapping_HasKey(c(m), c(key))
	clearErr();
	return ret > 0
}

func (m *MemoryView) HasKeyString(key string) bool {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_HasKeyString(c(m), cKey)
	clearErr();
	return ret > 0
}

func (m *MemoryView) DelItem(key Object) error {
	ret := C.PyObject_DelItem(c(m), c(key))
	return int2Err(ret)
}

func (m *MemoryView) DelItemString(key string) error {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyObject_DelItemString(c(m), cKey)
	return int2Err(ret)
}

func (m *MemoryView) SetItemString(key string, v Object) error {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_SetItemString(c(m), cKey, c(v))
	return int2Err(ret)
}

// AsSequenceMethods returns a SequenceMethods instance that refers to the same
// underlying Python object as m.
//
// This method also means that MemoryView implements the SequenceProtocol
// interface.
func (m *MemoryView) AsSequenceMethods() *SequenceMethods {
	return (*SequenceMethods)(unsafe.Pointer(m.Base()))
}

func (m *MemoryView) GetIndex(idx int) (Object, error) {
	ret := C.PySequence_GetItem(c(m), C.Py_ssize_t(idx))
	return obj2ObjErr(ret)
}

func (m *MemoryView) Count(obj Object) (int, error) {
	ret := C.PySequence_Count(c(m), c(obj))
	return ssize_t2IntErr(ret)
}

func (m *MemoryView) Index(obj Object) (int, error) {
	ret := C.PySequence_Index(c(m), c(obj))
	return ssize_t2IntErr(ret)
}

func (m *MemoryView) List() (*List, error) {
	ret := C.PySequence_List(c(m))
	if ret == nil {
		return nil, exception()
	}
	return newList(ret), nil
}

func (m *MemoryView) Tuple() (*Tuple, error) {
	ret := C.PySequence_Tuple(c(m))
	if ret == nil {
		return nil, exception()
	}
	return newTuple(ret), nil
}

func (m *MemoryView) GetSlice(start, end int) (Object, error) {
	ret := C.PySequence_GetSlice(c(m), C.Py_ssize_t(start), C.Py_ssize_t(end))
	return obj2ObjErr(ret)
}

func (m *MemoryView) SetSlice(start, end int, obj Object) error {
	ret := C.PySequence_SetSlice(c(m), C.Py_ssize_t(start), C.Py_ssize_t(end), c(obj))
	return int2Err(ret)
}

func (m *MemoryView) DelSlice(start, end int) error {
	ret := C.PySequence_DelSlice(c(m), C.Py_ssize_t(start), C.Py_ssize_t(end))
	return int2Err(ret)
}

// AsBufferMethods returns a BufferMethods instance that refers to the same
// underlying Python object as m.
//
// This method also means that MemoryView implements the BufferProtocol
// interface.
func (m *MemoryView) AsBufferMethods() *BufferMethods {
	return (*BufferMethods)(unsafe.Pointer(m.Base()))
}

func(m *MemoryView) GetBuffer(flags BufferFlags) (*Buffer, error) {
	buf := newBuffer()
	ret := C.PyObject_GetBuffer(c(m), buf.c(), C.int(flags))
	if ret < 0 {
		return nil, exception()
	}
	return buf, nil
}



/*
set fields:
  bf_getbuffer
  bf_releasebuffer
  mp_ass_subscript
  mp_length
  mp_subscript
  ob_base
  sq_item
  sq_length
  tp_as_buffer
  tp_as_mapping
  tp_as_sequence
  tp_basicsize
  tp_clear
  tp_dealloc
  tp_doc
  tp_flags
  tp_getattro
  tp_getset
  tp_hash
  tp_itemsize
  tp_iter
  tp_methods
  tp_name
  tp_new
  tp_repr
  tp_richcompare
  tp_traverse
  tp_weaklistoffset
*/

