// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

type Method struct {
	abstractObject
	o C.PyMethodObject
}

// MethodType is the Type object that represents the Method type.
var MethodType = (*Type)(unsafe.Pointer(&C.PyMethod_Type))

func methodCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.methodCheck(c(obj)) != 0
}

func newMethod(obj *C.PyObject) *Method {
	return (*Method)(unsafe.Pointer(obj))
}







/*
ob_base = true
tp_basicsize = true
tp_call = true
tp_dealloc = true
tp_doc = true
tp_flags = true
tp_getattro = true
tp_getset = true
tp_hash = true
tp_members = true
tp_methods = true
tp_name = true
tp_new = true
tp_repr = true
tp_richcompare = true
tp_setattro = true
tp_traverse = true
tp_vectorcall_offset = true
tp_weaklistoffset = true
*/

