// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// Method represents objects of the MethodType (or PyMethodType
// in the Python API) type.
type Method struct {
	abstractObject
	o C.PyMethodObject
}

// MethodType is the Type object that represents the Method type.
var MethodType = (*Type)(unsafe.Pointer(&C.PyMethod_Type))

func methodCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.methodCheck(c(obj)) != 0
}

func newMethod(obj *C.PyObject) *Method {
	return (*Method)(unsafe.Pointer(obj))
}



/*
set fields:
  ob_base
  tp_basicsize
  tp_call
  tp_dealloc
  tp_doc
  tp_flags
  tp_getattro
  tp_getset
  tp_hash
  tp_members
  tp_methods
  tp_name
  tp_new
  tp_repr
  tp_richcompare
  tp_setattro
  tp_traverse
  tp_vectorcall_offset
  tp_weaklistoffset
*/

