// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// NumberMethods is a concrete realisation of the full set of Number Protocol
// methods. A type that implements the "Number Protocol" can be turned into a
// NumberMethods instance using AsNumber.
//
// Note that the methods not already implemented on the type itself may return
// an error, as not all methods are implemented by all types that support the
// protocol.
type NumberMethods struct {
	o C.PyObject
}

var _ Object = (*NumberMethods)(nil)





func (n *NumberMethods) c() *C.PyObject {
	return (*C.PyObject)(unsafe.Pointer(n))
}

// Base returns a BaseObject pointer that gives access to the generic methods on
// that type for this object.
func (n *NumberMethods) Base() *BaseObject {
	return (*BaseObject)(unsafe.Pointer(n))
}

// Type returns a pointer to the Type that represents the type of this object in
// Python.
func (n *NumberMethods) Type() *Type {
	return newType(c(n).ob_type)
}

// Decref decrements n's reference count, n may not be nil.
func (n *NumberMethods) Decref() {
	C.decref(c(n))
}

// Incref increments n's reference count, n may not be nil.
func (n *NumberMethods) Incref() {
	C.incref(c(n))
}

// IsTrue returns true if the value of n is considered to be True. This is
// equivalent to "if n:" in Python.
func (n *NumberMethods) IsTrue() bool {
	ret := C.PyObject_IsTrue(c(n))
	if ret < 0 {
		panic(exception())
	}
	return ret != 0
}

// Not returns true if the value of n is considered to be False. This is
// equivalent to "if not n:" in Python.
func (n *NumberMethods) Not() bool {
	ret := C.PyObject_Not(c(n))
	if ret < 0 {
		panic(exception())
	}
	return ret != 0
}

// Free deallocates the storage (in Python) for n. After calling this method,
// n should no longer be used.
func (n *NumberMethods) Free() {
	free(n)
}



/*
set fields:
*/

