// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// Slice represents objects of the SliceType (or PySliceType
// in the Python API) type.
type Slice struct {
	abstractObject
	o C.PySliceObject
}

// SliceType is the Type object that represents the Slice type.
var SliceType = (*Type)(unsafe.Pointer(&C.PySlice_Type))

func sliceCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.sliceCheck(c(obj)) != 0
}

func newSlice(obj *C.PyObject) *Slice {
	return (*Slice)(unsafe.Pointer(obj))
}

// Repr returns a String representation of "s". This is equivalent to the
// Python "repr(s)".
//
// Return value: New Reference.
func (s *Slice) Repr() (Object, error) {
	ret := C.PyObject_Repr(c(s))
	return obj2ObjErr(ret)
}

// Hash computes and returns the hash value of s. The equivalent
// Python is "hash(s)".
func (s *Slice) Hash() (int, error) {
	ret := C.PyObject_Hash(c(s))
	if ret == -1 {
		return 0, exception()
	}
	return int(ret), nil
}



/*
set fields:
  ob_base
  tp_basicsize
  tp_dealloc
  tp_doc
  tp_flags
  tp_getattro
  tp_hash
  tp_members
  tp_methods
  tp_name
  tp_new
  tp_repr
  tp_richcompare
  tp_traverse
*/

