// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// Slice represents objects of the SliceType (or PySliceType
// in the Python API) type.
type Slice struct {
	abstractObject
	o C.PySliceObject
}

// SliceType is the Type object that represents the Slice type.
var SliceType = (*Type)(unsafe.Pointer(&C.PySlice_Type))

func sliceCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.sliceCheck(c(obj)) != 0
}

func newSlice(obj *C.PyObject) *Slice {
	return (*Slice)(unsafe.Pointer(obj))
}



/*
set fields:
  ob_base
  tp_basicsize
  tp_dealloc
  tp_doc
  tp_flags
  tp_getattro
  tp_hash
  tp_members
  tp_methods
  tp_name
  tp_new
  tp_repr
  tp_richcompare
  tp_traverse
*/

