// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// Tuple represents objects of the TupleType (or PyTuple_Type
// in the Python API) type.
//
// This type implements the Mapping protocol.
//
// This type implements the Sequence protocol.
type Tuple struct {
	o C.PyTupleObject
}

var _ Object = (*Tuple)(nil)

// TupleType is the Type object that represents the Tuple type.
var TupleType = newType(&C.PyTuple_Type)

func tupleCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.tupleCheck(c(obj)) != 0
}

// AsTuple casts the given obj to a Tuple (i.e. the underlying
// Python Object is the same, just the type is changed). If the value cannot be
// cast to a Tuple, then nil is returned.
//
// Return value: Borrowed Reference.
func AsTuple(obj Object) *Tuple {
	if obj == nil {
		return nil
	}
	o := c(obj)
	if C.tupleCheck(o) == 0 {
		return nil
	}
	return (*Tuple)(unsafe.Pointer(o))
}

func newTuple(obj *C.PyObject) *Tuple {
	return (*Tuple)(unsafe.Pointer(obj))
}



func (t *Tuple) c() *C.PyTupleObject {
	return (*C.PyTupleObject)(unsafe.Pointer(t))
}

// Base returns a BaseObject pointer that gives access to the generic methods on
// that type for this object.
func (t *Tuple) Base() *BaseObject {
	return (*BaseObject)(unsafe.Pointer(t))
}

// Type returns a pointer to the Type that represents the type of this object in
// Python.
func (t *Tuple) Type() *Type {
	return newType(c(t).ob_type)
}


// Decref decrements t's reference count, t may not be nil.
func (t *Tuple) Decref() {
	obj := (*C.PyObject)(unsafe.Pointer(t))
	refcnt := (*int)(unsafe.Pointer(&obj.anon0[0]))
	*refcnt--
	if *refcnt == 0 {
		C._Py_Dealloc(obj)
	}
}

// Incref increments t's reference count, t may not be nil.
func (t *Tuple) Incref() {
	refcnt := (*int)(unsafe.Pointer(&(*C.PyObject)(unsafe.Pointer(t)).anon0[0]))
	*refcnt++
}

// Repr returns a String representation of "t". This is equivalent to the
// Python "repr(t)".
//
// Return value: New Reference.
func (t *Tuple) Repr() (*Unicode, error) {
	ret := C.PyObject_Repr(c(t))
	if ret == nil {
		return nil, exception()
	}
	return newObject(ret).(*Unicode), nil
}

// Hash computes and returns the hash value of t. The equivalent
// Python is "hash(t)".
func (t *Tuple) Hash() (int, error) {
	ret := C.PyObject_Hash(c(t))
	if ret == -1 {
		return 0, exception()
	}
	return int(ret), nil
}

// HasAttr returns true if "t" has the attribute "name".  This is equivalent
// to the Python "hasattr(t, name)".
func (t *Tuple) HasAttr(name Object) bool {
	ret := C.PyObject_HasAttr(c(t), c(name))
	return ret == 1
}

// GetAttr returns the attribute of "t" with the name "name".  This is
// equivalent to the Python "t.name".
//
// Return value: New Reference.
func (t *Tuple) GetAttr(name Object) (Object, error) {
	ret := C.PyObject_GetAttr(c(t), c(name))
	return obj2ObjErr(ret)
}

// RichCompare compares "t" with "obj" using the specified operation (LE, GE
// etc.), and returns the result.  The equivalent Python is "t op obj", where
// op is the corresponding Python operator for op.
//
// Return value: New Reference.
func (t *Tuple) RichCompare(obj Object, op Op) (Object, error) {
	ret := C.PyObject_RichCompare(c(t), c(obj), C.int(op))
	return obj2ObjErr(ret)
}

// RichCompare compares "t" with "obj" using the specified operation (LE, GE
// etc.), and returns true or false.  The equivalent Python is "t op obj",
// where op is the corresponding Python operator for op.
func (t *Tuple) RichCompareBool(obj Object, op Op) (bool, error) {
	ret := C.PyObject_RichCompareBool(c(t), c(obj), C.int(op))
	return int2BoolErr(ret)
}

// Iter returns an Iterator that will iterate over the members of t.
func (t *Tuple) Iter() (Iterator, error) {
	ret := C.PyObject_GetIter(c(t))
	if ret == nil {
		return nil, exception()
	}
	return newIterator(ret)
}

// Size returns the size of t. The equivalent Python is "len(t)".
func (t *Tuple) Size() int {
	ret := C.PyObject_Size(c(t))
	if ret < 0 {
		clearErr();
		return 0
	}
	return int(ret)
}

// AsMappingMethods returns a MappingMethods instance that refers to the same
// underlying Python object as t.
//
// This method also means that Tuple implements the MappingProtocol interface.
func (t *Tuple) AsMappingMethods() *MappingMethods {
	return (*MappingMethods)(unsafe.Pointer(t.Base()))
}

func (t *Tuple) GetItemString(key string) (Object, error) {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_GetItemString(c(t), cKey)
	return obj2ObjErr(ret)
}

func (t *Tuple) HasKey(key Object) bool {
	ret := C.PyMapping_HasKey(c(t), c(key))
	clearErr();
	return ret > 0
}

func (t *Tuple) HasKeyString(key string) bool {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_HasKeyString(c(t), cKey)
	clearErr();
	return ret > 0
}

// AsSequenceMethods returns a SequenceMethods instance that refers to the same
// underlying Python object as t.
//
// This method also means that Tuple implements the SequenceProtocol
// interface.
func (t *Tuple) AsSequenceMethods() *SequenceMethods {
	return (*SequenceMethods)(unsafe.Pointer(t.Base()))
}

func (t *Tuple) GetIndex(idx int) (Object, error) {
	ret := C.PySequence_GetItem(c(t), C.Py_ssize_t(idx))
	return obj2ObjErr(ret)
}

func (t *Tuple) Count(obj Object) (int, error) {
	ret := C.PySequence_Count(c(t), c(obj))
	return ssize_t2IntErr(ret)
}

func (t *Tuple) Index(obj Object) (int, error) {
	ret := C.PySequence_Index(c(t), c(obj))
	return ssize_t2IntErr(ret)
}

func (t *Tuple) List() (*List, error) {
	ret := C.PySequence_List(c(t))
	if ret == nil {
		return nil, exception()
	}
	return newList(ret), nil
}

func (t *Tuple) Concat(obj Object) (Object, error) {
	ret := C.PySequence_Concat(c(t), c(obj))
	return obj2ObjErr(ret)
}

func (t *Tuple) Repeat(count int) (Object, error) {
	ret := C.PySequence_Repeat(c(t), C.Py_ssize_t(count))
	return obj2ObjErr(ret)
}

func (t *Tuple) Contains(obj Object) (bool, error) {
	ret := C.PySequence_Contains(c(t), c(obj))
	return int2BoolErr(ret)
}

func (t *Tuple) GetSlice(start, end int) (Object, error) {
	ret := C.PySequence_GetSlice(c(t), C.Py_ssize_t(start), C.Py_ssize_t(end))
	return obj2ObjErr(ret)
}



/*
set fields:
  mp_length
  mp_subscript
  ob_base
  sq_concat
  sq_contains
  sq_item
  sq_length
  sq_repeat
  tp_as_mapping
  tp_as_sequence
  tp_basicsize
  tp_dealloc
  tp_doc
  tp_flags
  tp_free
  tp_getattro
  tp_hash
  tp_itemsize
  tp_iter
  tp_methods
  tp_name
  tp_new
  tp_repr
  tp_richcompare
  tp_traverse
  tp_vectorcall
*/

