// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// Tuple represents objects of the TupleType (or PyTupleType
// in the Python API) type.
//
// This type implements the Mapping protocol.
//
// This type implements the Sequence protocol.
type Tuple struct {
	abstractObject
	o C.PyTupleObject
}

// TupleType is the Type object that represents the Tuple type.
var TupleType = (*Type)(unsafe.Pointer(&C.PyTuple_Type))

func tupleCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.tupleCheck(c(obj)) != 0
}

func newTuple(obj *C.PyObject) *Tuple {
	return (*Tuple)(unsafe.Pointer(obj))
}

func (t *Tuple) Size() int {
	ret := C.PyObject_Size(c(t))
	if ret < 0 {
		clearErr();
		return 0
	}
	return int(ret)
}

func (t *Tuple) AsMapping() *MappingMethods {
	return (*MappingMethods)(unsafe.Pointer(t.Base()))
}

func (t *Tuple) GetItemString(key string) (Object, error) {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_GetItemString(c(t), cKey)
	return obj2ObjErr(ret)
}

func (t *Tuple) HasKey(key Object) bool {
	ret := C.PyMapping_HasKey(c(t), c(key))
	clearErr();
	return ret > 0
}

func (t *Tuple) HasKeyString(key string) bool {
	cKey := C.CString(key)
	defer C.free(unsafe.Pointer(cKey))
	ret := C.PyMapping_HasKeyString(c(t), cKey)
	clearErr();
	return ret > 0
}

func (t *Tuple) AsSequence() *SequenceMethods {
	return (*SequenceMethods)(unsafe.Pointer(t.Base()))
}

func (t *Tuple) GetIndex(idx int) (Object, error) {
	ret := C.PySequence_GetItem(c(t), C.Py_ssize_t(idx))
	return obj2ObjErr(ret)
}

func (t *Tuple) Count(obj Object) (int, error) {
	ret := C.PySequence_Count(c(t), c(obj))
	return ssize_t2IntErr(ret)
}

func (t *Tuple) Index(obj Object) (int, error) {
	ret := C.PySequence_Index(c(t), c(obj))
	return ssize_t2IntErr(ret)
}

func (t *Tuple) List() (*List, error) {
	ret := C.PySequence_List(c(t))
	if ret == nil {
		return nil, exception()
	}
	return newList(ret), nil
}

func (t *Tuple) Concat(obj Object) (Object, error) {
	ret := C.PySequence_Concat(c(t), c(obj))
	return obj2ObjErr(ret)
}

func (t *Tuple) Repeat(count int) (Object, error) {
	ret := C.PySequence_Repeat(c(t), C.Py_ssize_t(count))
	return obj2ObjErr(ret)
}

func (t *Tuple) Contains(obj Object) (bool, error) {
	ret := C.PySequence_Contains(c(t), c(obj))
	return int2BoolErr(ret)
}

func (t *Tuple) GetSlice(start, end int) (Object, error) {
	ret := C.PySequence_GetSlice(c(t), C.Py_ssize_t(start), C.Py_ssize_t(end))
	return obj2ObjErr(ret)
}



/*
set fields:
  mp_length
  mp_subscript
  ob_base
  sq_concat
  sq_contains
  sq_item
  sq_length
  sq_repeat
  tp_as_mapping
  tp_as_sequence
  tp_basicsize
  tp_dealloc
  tp_doc
  tp_flags
  tp_free
  tp_getattro
  tp_hash
  tp_itemsize
  tp_iter
  tp_methods
  tp_name
  tp_new
  tp_repr
  tp_richcompare
  tp_traverse
  tp_vectorcall
*/

