// Code generated by gen_types. DO NOT EDIT.

package py

// #include "utils.h"
import "C"

import (
	"unsafe"
)

// Type represents objects of the TypeType (or PyTypeType
// in the Python API) type.
type Type struct {
	abstractObject
	o C.PyTypeObject
}

// TypeType is the Type object that represents the Type type.
var TypeType = (*Type)(unsafe.Pointer(&C.PyType_Type))

func typeCheck(obj Object) bool {
	if obj == nil {
		return false
	}
	return C.typeCheck(c(obj)) != 0
}

func newType(obj *C.PyObject) *Type {
	return (*Type)(unsafe.Pointer(obj))
}



/*
set fields:
  nb_or
  ob_base
  tp_as_number
  tp_basicsize
  tp_call
  tp_clear
  tp_dealloc
  tp_dictoffset
  tp_doc
  tp_flags
  tp_free
  tp_getattro
  tp_getset
  tp_init
  tp_is_gc
  tp_itemsize
  tp_members
  tp_methods
  tp_name
  tp_new
  tp_repr
  tp_setattro
  tp_traverse
  tp_vectorcall
  tp_vectorcall_offset
  tp_weaklistoffset
*/

