// Code generated by gen_types.py. DO NOT EDIT.

#ifndef _GO_PYTHON_TYPES_H_
#define _GO_PYTHON_TYPES_H_

#include <ffi.h>
#include <python3.11/Python.h>
#include <python3.11/frameobject.h>

// ===============================================================

extern int aIterCheck(PyObject *o);
extern int anySetCheck(PyObject *o);
extern int boolCheck(PyObject *o);
extern int byteArrayCheck(PyObject *o);
extern int bytesCheck(PyObject *o);
extern int cFunctionCheck(PyObject *o);
extern int cMethodCheck(PyObject *o);
extern int callIterCheck(PyObject *o);
extern int callableCheck(PyObject *o);
extern int cellCheck(PyObject *o);
extern int codeCheck(PyObject *o);
extern int complexCheck(PyObject *o);
extern int dictCheck(PyObject *o);
extern int dictItemsCheck(PyObject *o);
extern int dictKeysCheck(PyObject *o);
extern int dictValuesCheck(PyObject *o);
extern int dictViewSetCheck(PyObject *o);
extern int exceptionClassCheck(PyObject *o);
extern int exceptionInstanceCheck(PyObject *o);
extern int floatCheck(PyObject *o);
extern int frameCheck(PyObject *o);
extern int frozenSetCheck(PyObject *o);
extern int functionCheck(PyObject *o);
extern int genCheck(PyObject *o);
extern int indexCheck(PyObject *o);
extern int instanceMethodCheck(PyObject *o);
extern int iterCheck(PyObject *o);
extern int listCheck(PyObject *o);
extern int longCheck(PyObject *o);
extern int mappingCheck(PyObject *o);
extern int memoryViewCheck(PyObject *o);
extern int methodCheck(PyObject *o);
extern int moduleCheck(PyObject *o);
extern int numberCheck(PyObject *o);
extern int oDictCheck(PyObject *o);
extern int pickleBufferCheck(PyObject *o);
extern int rangeCheck(PyObject *o);
extern int seqIterCheck(PyObject *o);
extern int sequenceCheck(PyObject *o);
extern int setCheck(PyObject *o);
extern int sliceCheck(PyObject *o);
extern int traceBackCheck(PyObject *o);
extern int tupleCheck(PyObject *o);
extern int typeCheck(PyObject *o);
extern int unicodeCheck(PyObject *o);
extern int weakrefCheck(PyObject *o);
extern int anySetCheckE(PyObject *o);
extern int asyncGenCheckE(PyObject *o);
extern int byteArrayCheckE(PyObject *o);
extern int bytesCheckE(PyObject *o);
extern int cFunctionCheckE(PyObject *o);
extern int cMethodCheckE(PyObject *o);
extern int capsuleCheckE(PyObject *o);
extern int complexCheckE(PyObject *o);
extern int contextCheckE(PyObject *o);
extern int contextTokenCheckE(PyObject *o);
extern int contextVarCheckE(PyObject *o);
extern int coroCheckE(PyObject *o);
extern int dictCheckE(PyObject *o);
extern int floatCheckE(PyObject *o);
extern int frozenSetCheckE(PyObject *o);
extern int genCheckE(PyObject *o);
extern int listCheckE(PyObject *o);
extern int longCheckE(PyObject *o);
extern int moduleCheckE(PyObject *o);
extern int oDictCheckE(PyObject *o);
extern int setCheckE(PyObject *o);
extern int tupleCheckE(PyObject *o);
extern int typeCheckE(PyObject *o);
extern int unicodeCheckE(PyObject *o);

// ===============================================================
// ===============================================================

// --- types.go helper functions ---
//
extern PyTypeObject *getBasePyType(PyObject *o);
//
// ----------------------------------

// ===============================================================

#endif /* _GO_PYTHON_TYPES_H */
