// Code generated by gen_extension. DO NOT EDIT.

package main

// #cgo pkg-config: python-3.14-embed
// #include <python3.14/Python.h>
import "C"

import (
	"unsafe"

	"gopython.xyz/py/v14"
)

//export PyInit_extension
func PyInit_extension() *C.PyObject {
	return (*C.PyObject)(unsafe.Pointer(py.InitExtension(initExtension)))
}