# Copyright 2011 Julian Phillips.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=lib

CGOFILES=\
	object.go \
	module.go \
	arg.go \
	err.go \
	class.go \
	tuple.go \
	int.go \
	dict.go \
	string.go \
	bool.go \
	list.go \
	long.go \
	python.go

CGO_OFILES=\
	utils.o

include $(GOROOT)/src/Make.pkg
