# Copyright 2011 Julian Phillips.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=github.com/qur/gopy/lib

CGOFILES=\
	abstract.go \
	arg.go \
	base.go \
	bool.go \
	cfunction.go \
	chan.go \
	class.go \
	class_mapping.go \
	class_number.go \
	class_sequence.go \
	class_standard.go \
	code.go \
	complex.go \
	dict.go \
	err.go \
	eval.go \
	float.go \
	gomod.go \
	int.go \
	list.go \
	lock.go \
	long.go \
	module.go \
	object.go \
	run.go \
	string.go \
	tuple.go \
	type.go \
	python.go

CGO_OFILES=\
	utils.o

include $(GOROOT)/src/Make.pkg
