// Code generated by gen_types.py. DO NOT EDIT.

package main

// #cgo CFLAGS: -Werror
// #cgo LDFLAGS: -lpython3.11 -lm -lutil -ldl
// #cgo pkg-config: libffi
//
// #include <python3.11/Python.h>
import "C"

// ===============================================================

var types = map[string]any{
	"ByteArray": C.PyByteArray_Type,
	"Bytes": C.PyBytes_Type,
	"CFunction": C.PyCFunction_Type,
	"CMethod": C.PyCMethod_Type,
	"Cell": C.PyCell_Type,
	"Code": C.PyCode_Type,
	"Complex": C.PyComplex_Type,
	"Dict": C.PyDict_Type,
	"DictKeys": C.PyDictKeys_Type,
	"Float": C.PyFloat_Type,
	"Frame": C.PyFrame_Type,
	"Function": C.PyFunction_Type,
	"Gen": C.PyGen_Type,
	"InstanceMethod": C.PyInstanceMethod_Type,
	"List": C.PyList_Type,
	"Long": C.PyLong_Type,
	"MemoryView": C.PyMemoryView_Type,
	"Method": C.PyMethod_Type,
	"ODict": C.PyODict_Type,
	"Set": C.PySet_Type,
	"Slice": C.PySlice_Type,
	"Tuple": C.PyTuple_Type,
	"Type": C.PyType_Type,
	"Unicode": C.PyUnicode_Type,
}

// ===============================================================
