# Copyright 2011 Julian Phillips.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=gopysh

GOFILES=\
	commands.go \
	exec.go \
	main.go \
	module.go \
	parse.go \
	python.go \

include $(GOROOT)/src/Make.cmd
